# Generated by Django 4.2.1 on 2023-06-30 16:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricão', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='imagem_cultura')),
                ('cidade', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricão', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='imagem_gastronomia')),
                ('cidade', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricão', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='imagem_natureza')),
                ('cidade', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Praia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricão', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='imagem_praia')),
                ('cidade', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(default=datetime.date(2023, 6, 30))),
                ('cultura', models.ManyToManyField(blank=True, to='treep.cultura')),
                ('gastronomia', models.ManyToManyField(blank=True, to='treep.gastronomia')),
                ('natureza', models.ManyToManyField(blank=True, to='treep.natureza')),
                ('praia', models.ManyToManyField(blank=True, to='treep.praia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
