# Generated by Django 4.2.1 on 2023-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='posicao',
            field=models.IntegerField(default=0),
        ),
    ]
